module.exports = [
    {
        name:'hk1',
        aes:'aes-256-cfb',
        port:27752,
        password:'KTnE5N'
    },
    {
        name:'hk2',
        aes:'aes-256-cfb',
        port:27752,
        password:'KTnE5N'
    },
    {
        name:'hk3',
        aes: 'rc4-md5',
        port:27752,
        password:'KTnE5N'
    },
    {
        name:'jp1',
        aes:'aes-256-cfb',
        port:27752,
        password:'KTnE5N'
    },
    {
        name:'jp2',
        aes:'aes-256-cfb',
        port:27752,
        password:'KTnE5N'
    },
    {
        name:'us1',
        aes:'aes-256-cfb',
        port:27752,
        password:'KTnE5N'
    },
    {
        name:'us3',
        aes:'aes-256-cfb',
        port:27752,
        password:'KTnE5N'
    }
];